function [time,lat,lon,alt,v_e,v_n,v_v,roll,pitch,heading,gps_t,gps_t_valid,ahrs_valid,lat_err,lon_err,alt_err,v_e_err,v_n_err,v_v_err,roll_err,pitch_err,heading_err, satellites] = import_ahrs(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,LAT,LON,ALT,V_E,V_N,V_V,ROLL,PITCH,HEADING,GPS_T,GPS_T_VALID,AHRS_VALID,LAT_ERR,LON_ERR,ALT_ERR,V_E_ERR,V_N_ERR,V_V_ERR,ROLL_ERR,PITCH_ERR,HEADING_ERR, SATELLITES]
%   = IMPORT_AHRS(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,LAT,LON,ALT,V_E,V_N,V_V,ROLL,PITCH,HEADING,GPS_T,GPS_T_VALID,AHRS_VALID,LAT_ERR,LON_ERR,ALT_ERR,V_E_ERR,V_N_ERR,V_V_ERR,ROLL_ERR,PITCH_ERR,HEADING_ERR, SATELLITES]
%   = IMPORT_AHRS(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [time,lat,lon,alt,v_e,v_n,v_v,roll,pitch,heading,tow,gps_t_valid,gps,ahrs_valid,lat_err,lon_err,alt_err,v_e_err,v_n_err,v_v_err,roll_err,pitch_err,heading_err]
%   = import_ahrs('AHRSTELEM_20131202T203000.slapdlm',1, 14999);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/12/03 08:09:12 - updated for OxTS format

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: date strings (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: date strings (%s)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%s%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Convert the contents of column with dates to serial date numbers using date format string (datenum).
dataArray{1} = datenum(dataArray{1}, 'HH:MM:SS.FFF mm/dd/yyyy');
dataArray{11} = datenum(dataArray{11}, 'HH:MM:SS.FFF mm/dd/yyyy');

%% Allocate imported array to column variable names
time = dataArray{:, 1};
lat = dataArray{:, 2};
lon = dataArray{:, 3};
alt = dataArray{:, 4};
v_e = dataArray{:, 5};
v_n = dataArray{:, 6};
v_v = dataArray{:, 7};
roll = dataArray{:, 8};
pitch = dataArray{:, 9};
heading = dataArray{:, 10};
gps_t = dataArray{:, 11};
gps_t_valid = dataArray{:, 12};
ahrs_valid = dataArray{:, 13};
lat_err = dataArray{:, 14};
lon_err = dataArray{:, 15};
alt_err = dataArray{:, 16};
v_e_err = dataArray{:, 17};
v_n_err = dataArray{:, 18};
v_v_err = dataArray{:, 19};
roll_err = dataArray{:, 20};
pitch_err = dataArray{:, 21};
heading_err = dataArray{:, 22};
satellites = dataArray{:, 23};

